---
title: "UAE18 crypto communities"
author: "Simon J Brandl"
date: "11/22/2018"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r LOAD PACKAGES}
#load packages
library(plyr)
library(dplyr)
library(tidyverse)
library(vegan)
library(nlme)
library(lme4)
library(ggpubr)
library(ggrepel)
library(colorRamps)
library(tidybayes)
library(brms)
library(fishualize)
library(modelr)
library(beepr)
library(png)
library(grid)
library(scales)
library(iNEXT)
library(geomnet)
library(GGally)
library(extrafont)
library(xgboost)
devtools::load_all("rfishprod")
```

```{r LOAD DATASETS AND SILHOUETTES}
#load datasets
comms <- read.csv(file = "Data/UAE18_RawData_Comms.csv")
ctdat <- read.csv(file = "Data/UAE_CT.csv")
benthcomm <- read.csv(file = "Data/benthic_commcomp.csv")
comms$Genspe <- paste(substr(comms$Genus, 0,3), comms$Species, sep = ". ")
ctdat$Genspe <- paste(substr(ctdat$Genus, 0,3), ctdat$Species, sep = ". ")
ctdat <- ctdat %>% mutate(Distribution = case_when(Tax == "ECSEPULC" ~ "AG+GoM",
                                         Tax == "CORYANOM" ~ "AG+GoM",
                                         Tax == "ENNEVENT" ~ "AG+GoM",
                                         Tax == "HELCFUSC" ~ "GoM",
                                         Tax == "HETEVULG" ~ "GoM",
                                         Tax == "EVIOGUTT" ~ "GoM"))
ctmax <- subset(ctdat, ctdat$Ctmax != "NA")
ctmin <- subset(ctdat, ctdat$Ctmin != "NA")

# silhouettes for study species
img <- readPNG("Plots/Canomalus.png")
canom <- rasterGrob(img, interpolate=TRUE)

img <- readPNG("Plots/Epulcher.png")
epulc <- rasterGrob(img, interpolate=TRUE)

img <- readPNG("Plots/Eventermaculus.png")
event <- rasterGrob(img, interpolate=TRUE)

img <- readPNG("Plots/Hvulgaris.png")
hvulg <- rasterGrob(img, interpolate=TRUE)

img <- readPNG("Plots/Eguttata.png")
egutt<- rasterGrob(img, interpolate=TRUE)

img <- readPNG("Plots/Hfuscopinna.png")
hfusc <- rasterGrob(img, interpolate=TRUE)


uaecols <- fish(n = 2, option = "Trimma_lantana", end = 0.3)
image(volcano, col = uaecols)
```

```{r COMMUNITY STRUCTURE: ABUNDANCE, BIOMASS, DIVERSITY}
#start with community analyses
# 1. compare abundance, biomass, diversity
# 2. compare community composition
# calculate surface area for each bommie 
# radius first (2*curved surface length/2*pi)
comms$radius <- (2*comms$Dimension)/(2*pi)
# surface area (4*pi*radius^2)/2 and divide by 10000 for square meters
comms$SA <- ((4*pi*comms$radius^2)/2)/10000

###get biomass and diversity estimates for Arabian Gulf and Gulf of Oman
comm_means <- comms %>% group_by(Location, Site, Sitename, Sitenumber) %>% summarize(Biomass = sum(W), Abundance = n(), Speciesrichness = length(unique(Genspe)), SA = mean(SA)) %>%
  mutate(Density = Abundance/SA,
         Biomass_per_m2 = Biomass/SA,
         Species_density = Speciesrichness/SA,
         site_intercepts = case_when(Site == "Dhabiya" ~ 1.90,
                                     Site == "RasGhanada" ~ 1.80,
                                     Site == "Saadiyat" ~ 1.70,
                                     Site == "Dibba" ~ 0.9,
                                     Site == "SharmRock" ~ 0.80,
                                     Site == "Snoopy" ~ 0.70),
         site_reord = factor(Site, levels = sort(levels(site_intercepts))))


#run GLM with abundance data and offset for surface area sampled
abundance.model <- brm(log(Density) ~ Location + (1|Site), 
                            data = comm_means, control = list(adapt_delta = 0.999, max_treedepth = 15))
summary(abundance.model)
abu.pred <- comm_means %>%
  data_grid(Location) %>%
  add_predicted_draws(abundance.model, n = 1000) %>%
  mutate(pred.density = exp(.prediction))

abu.median <- abu.pred %>%
  group_by(Location) %>%
  summarize(median = median(pred.density), sd = sd(pred.density)) %>%
  mutate(se = sd/sqrt(18))
abu.median

abu.pred.plot <- ggplot(data = abu.pred) +
  geom_halfeyeh(aes(y = rev(Location), x = pred.density, fill = Location), color = "black") +
  geom_jitter(aes(x = Density, y = site_intercepts, shape = reorder(Site, sort(as.numeric(site_intercepts))), fill = Location), color = "black", 
             data = comm_means, height = 0.02, 
             alpha = 0.5, size = 0.8) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = alpha(uaecols, 0.5)) +
  scale_shape_manual(name = "Site", values = c(21,22,23,21,22,23)) +
  scale_x_log10(limits = c(0.1,5e2), breaks=c(0,0.1,1,10,100), labels=c(0,0.1,1,10,100)) +
  theme_sjb() +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "top",
        legend.box = "vertical") +
  guides(fill = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1)) +
  xlab(expression(paste("Density of cryptobenthic fishes (individuals ", m^{-2},")")))+
  annotate("text", x = 0.1, y = 2.7, size = 3, label = "(b)", color = "black")
abu.pred.plot

ggsave("Plots/abupred.pdf", abu.pred.plot, width = 8, height = 4, useDingbats = F)


###############biomass

#run GLM with abundance data and offset for surface area sampled
biomass.model <- brm(log(Biomass_per_m2) ~ Location + (1|Site), 
                            data = comm_means, 
                     control = list(adapt_delta = 0.9999, max_treedepth = 15))
summary(biomass.model)
bio.pred <- comm_means %>%
  data_grid(Location) %>%
  add_predicted_draws(biomass.model, n = 1000) %>%
  mutate(pred.biomass = exp(.prediction))

bio.median <- bio.pred %>%
  group_by(Location) %>%
  summarize(median = median(pred.biomass), sd = sd(pred.biomass)) %>%
  mutate(se = sd/sqrt(18))
bio.median

bio.pred.plot <- ggplot(data = bio.pred) +
  geom_halfeyeh(aes(y = rev(Location), x = pred.biomass, fill = Location), color = "black") +
  geom_jitter(aes(x = Biomass_per_m2, y = site_intercepts, shape = reorder(Site, sort(as.numeric(site_intercepts))), fill = Location), color = "black", 
             data = comm_means, height = 0.02, 
             alpha = 0.5, size = 0.8) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = alpha(uaecols, 0.5)) +
  scale_shape_manual(name = "Site", values = c(21,22,23,21,22,23)) +
  scale_x_log10(limits = c(0.1,1e3), breaks=c(0,0.1,1,10,100,1000), labels=c(0,0.1,1,10,100,1000)) +
  theme_sjb() +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "top",
        legend.box = "vertical") +
  guides(fill = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1)) +
  xlab(expression(paste("Biomass of cryptobenthic fishes (grams ", m^{-2},")")))+
  annotate("text", x = 0.1, y = 2.7, size = 3, label = "(c)", color = "black")

bio.pred.plot

ggsave("Plots/biopred.pdf", bio.pred.plot, width = 8, height = 4, useDingbats = F)


###############biomass

#run GLM with abundance data and offset for surface area sampled
diversity.model <- brm(log(Species_density) ~ Location + (1|Site), 
                            data = comm_means,
                     control = list(adapt_delta = 0.999, max_treedepth = 15))
summary(diversity.model)
div.pred <- comm_means %>%
  data_grid(Location) %>%
  add_predicted_draws(diversity.model, n = 1000) %>%
  mutate(pred.diversity = exp(.prediction))

div.median <- div.pred %>%
  group_by(Location) %>%
  summarize(median = median(pred.diversity), sd = sd(pred.diversity)) %>%
  mutate(se = sd/sqrt(18))
div.median

div.pred.plot <- ggplot(data = div.pred) +
  geom_halfeyeh(aes(y = rev(Location), x = pred.diversity, fill = Location), color = "black") +
  geom_jitter(aes(x = Species_density, y = site_intercepts, shape = reorder(Site, sort(as.numeric(site_intercepts))), fill = Location), color = "black", 
             data = comm_means, height = 0.02, 
             alpha = 0.5, size = 0.8) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = alpha(uaecols, 0.5)) +
  scale_shape_manual(name = "Site", values = c(21,22,23,21,22,23)) +
  scale_x_log10(limits = c(0.1,100), breaks=c(0,0.1,1,10,100), labels=c(0,0.1,1,10,100)) +
  theme_sjb() +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "top",
        legend.spacing.y = unit(0.01, 'cm'),
        legend.spacing.x = unit(0.02, 'cm')) +
  guides(fill = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1)) +
  xlab(expression(paste("Species richness of cryptobenthic fishes (species ", m^{-2},")"))) +
  annotate("text", x = 0.1, y = 2.7, size = 3, label = "(a)", color = "black")
       
div.pred.plot

ggsave("Plots/divpred.pdf", div.pred.plot, width = 8, height = 4, useDingbats = F)

#function for legend
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

mylegend<-g_legend(div.pred.plot)

Fig1 <- gbm::grid.arrange(mylegend, gridExtra::arrangeGrob(div.pred.plot + theme(legend.position="none"),
                         abu.pred.plot + theme(legend.position="none"),
                         bio.pred.plot + theme(legend.position="none"),
                         nrow=3),
            nrow=2, heights=c(0.5, 12))

ggsave("Plots/Fig1_MS.png", Fig1, width = 7, height = 7)
```

```{r COMMUNITY COMPOSITION NMDS}
comms$count = 1
comms_wide <- comms %>% 
  group_by(Location, Site, Sitenumber, Genspe) %>%
  summarize(totaln = sum(count)) %>%
  spread(Genspe, totaln, fill = 0) 

###run MDS
comp_mds <- metaMDS(comms_wide[-c(1:3)], metric = "bray", trymax = 1000)
comp_mds
stressplot(comp_mds)

###get values and plot in ggplot
site.scores <- as.tibble(scores(comp_mds)) %>%
  mutate(Location = comms_wide$Location,
         Site = comms_wide$Site,
         Sitenumber = comms_wide$Sitenumber) %>% 
  inner_join(comm_means)



mds.points <- as.data.frame(scores(comp_mds, "species")) %>%
  add_column(Genspe = rownames(.))

genspeabu <- comms %>%
  group_by(Genspe, Family) %>%
  summarize(count = n()) %>%
  inner_join(mds.points)

point.plot <- ggplot(genspeabu) +
  theme_bw() +
  geom_segment(aes(x=0, xend=NMDS1, y=0, yend=NMDS2, color = Family),
               arrow = arrow(length = unit(0.1, "cm")),
               inherit.aes = F) +
  geom_text_repel(aes(x=NMDS1, NMDS2, label=Genspe), size=2, inherit.aes = F) +
  scale_color_fish(discrete=TRUE, option = "Valenciennea_strigata")
point.plot
###create convex hulls function
convex_hull <- function(site.scores) site.scores[chull(site.scores$NMDS1, site.scores$NMDS2),] 

###run convex hulls on habitats
location_hulls <- ddply(site.scores, "Location", convex_hull)


###create vector with habitat names in center of convex hulls
location_centers <- location_hulls %>% group_by(Location) %>% summarize(NMDS1 = mean(NMDS1), NMDS2 = mean(NMDS2))

###plot mds results
# plot one species name
comp_plot <- ggplot(site.scores, aes(x = NMDS1, y = NMDS2)) +
  #overlay convex hulls
  geom_polygon(data = location_hulls, aes(x = NMDS1, y = NMDS2, 
                                         fill = Location, 
                                         group = Location), 
               alpha = 0.4, lty = 1, lwd = 0.1, color = "black") +
  #overlay points
  geom_point(aes(color = Location, group = Location, fill = Location,
                             shape = reorder(Site, sort(as.numeric(site_intercepts))))) +
  theme_sjb()+
  theme(legend.position = "right",
        legend.title.align = 0) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  scale_shape_manual(name = "Site", values = c(21,22,23,21,22,23)) +
    guides(fill = guide_legend(ncol = 1),
         shape = guide_legend(ncol = 1)) +
  scale_y_continuous(limits = c(-0.8, 0.8), breaks = seq(-0.8,0.8,0.4)) +
  scale_x_continuous(limits = c(-1, 1), breaks = seq(-1,1,0.5)) 

comp_plot
ggsave("Plots/Fig2_MS.png", plot = comp_plot, width = 6, height = 4)
```

```{r SIZE: E. ventermaculis and C. anomalus}
size.strs <- read.csv(file = "Data/UAE_cryptosize_comb.csv")
t <- table(comms$Tax, comms$Location)
size.strs.event <- size.strs %>%
  filter(Species %in% c("ENNEVENT")) 

size.model.event <- brm(log(W) ~ (log(TL) + Location), data = size.strs.event)
summary(size.model.event)

size.preds.event <- size.strs.event %>%
  group_by(Location) %>%  
  data_grid(TL = seq_range(TL, n = 100)) %>%
  add_fitted_draws(size.model.event, n = 500) %>%
  mutate(backtrans = exp(.value))

event.plot <- ggplot(size.preds.event, aes(x = TL, y = W, color = ordered(Location))) +
  geom_point(data = size.strs.event, aes(fill = Location), alpha = 0.8, size = 1.2, shape = 23, color = "black", stroke = 0.1) +
  geom_line(aes(y = backtrans, group = paste(Location, .draw)), alpha = .1, lwd = 0.1) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  ylab("Body weight in g") +
  xlab("Total length (TL) in mm") +
  theme_sjb() +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0,0.4), breaks = seq(0,0.4,0.1)) +
  scale_x_continuous(limits = c(10,32), breaks = seq(10,32,2.5)) +
  annotate("text", x = 10, y = 0.4, size = 3, label = "(a)")
event.plot


size.strs.canom <- size.strs %>%
  filter(Species %in% c("CORYANOM")) %>%
  filter(TL < 50)
size.strs.canom = size.strs.canom[-134,]

size.model.canom <- brm(log(W) ~ (log(TL) + Location), data = size.strs.canom)
summary(size.model.canom)

size.preds.canom <- size.strs.canom %>%
  group_by(Location) %>%  
  data_grid(TL = seq_range(TL, n = 100)) %>%
  add_fitted_draws(size.model.canom, n = 500) %>%
  mutate(backtrans = exp(.value))

canom.plot <- ggplot(size.preds.canom, aes(x = TL, y = W, color = ordered(Location))) +
  geom_point(data = size.strs.canom, aes(fill = Location), size = 1.2, alpha = 0.8, shape = 23, color = "black", stroke = 0.1) +
  geom_line(aes(y = backtrans, group = paste(Location, .draw)), alpha = .1, lwd = 0.1) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  ylab("Body weight in g") +
  xlab("Total length (TL) in mm") +
  theme_sjb() +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0,1), breaks = seq(0,1,0.25)) +
  scale_x_continuous(limits = c(10,42), breaks = seq(10,42,10)) +
  annotate("text", x = 10, y = 1, size = 3, label = "(b)")
canom.plot

size.strs.epulc <- size.strs %>%
  filter(Species %in% c("ECSEPULC")) 

size.model.epulc <- brm(log(W) ~ (log(TL) + Location), data = size.strs.epulc)
summary(size.model.epulc)

size.preds.epulc <- size.strs.epulc %>%
  group_by(Location) %>%  
  data_grid(TL = seq_range(TL, n = 100)) %>%
  add_fitted_draws(size.model.epulc, n = 500) %>%
  mutate(backtrans = exp(.value))

epulc.plot <- ggplot(size.preds.epulc, aes(x = TL, y = W, color = ordered(Location))) +
  geom_point(data = size.strs.epulc, aes(fill = Location), size = 1.2, alpha = 0.8, shape = 23, color = "black", stroke = 0.1) +
  geom_line(aes(y = backtrans, group = paste(Location, .draw)), alpha = .1, lwd = 0.1) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  ylab("Body weight in g") +
  xlab("Total length (TL) in mm") +
  theme_sjb() +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0,5), breaks = seq(0,5,1)) +
  scale_x_continuous(limits = c(15,85), breaks = seq(15,85,10)) +
  annotate("text", x = 15, y = 5, size = 3, label = "(c)")
epulc.plot


Fig6 <- ggarrange(event.plot, canom.plot, epulc.plot, ncol = 1, nrow = 3)
ggsave("Plots/Fig6_MS.png", Fig6, width = 3, height = 6)
###comp abundance of three species in AG & GoO
```

```{r PHYSIOLOGY: CTmax and CTmin}
# ct max and ctmin
ctmax <- ctmax %>%
    mutate(ordervar = case_when(Tax == "CORYANOM" ~ 6,
                              Tax == "ECSEPULC" ~ 5,
                              Tax == "ENNEVENT" ~ 4,
                              Tax == "HETEVULG" ~ 3,
                              Tax == "EVIOGUTT" ~ 2,
                              TRUE ~ 1),
           taxloc = factor(interaction(Tax, Location)))

table(ctmax$taxloc)

maxmod <- brm(Ctmax ~ taxloc, data = ctmax,  control = list(adapt_delta = 0.995, max_treedepth = 18), iter = 5000);beep(sound = "coin")
summary(maxmod)

ctmax.pred <- ctmax %>%
  data_grid(taxloc)%>%  
  add_predicted_draws(maxmod, n = 10000) %>%
  separate(taxloc, c("Tax", "Location"), remove = F) %>%
  mutate(ordervar = case_when(Tax == "CORYANOM" ~ 6,
                              Tax == "ECSEPULC" ~ 5,
                              Tax == "ENNEVENT" ~ 4,
                              Tax == "HETEVULG" ~ 3,
                              Tax == "EVIOGUTT" ~ 2,
                              TRUE ~ 1))

ctmax.pred.plot <- ggplot(data = ctmax.pred) +
  geom_halfeyeh(aes(y = ordervar, x = .prediction, fill = Location), color = "black")+
  geom_jitter(aes(x = Ctmax, y = ordervar, shape = Tax, fill = Location),
             data = ctmax, size = 1.5, color = "black", shape = 23, height = 0.1, stroke = 0.1) +
  scale_color_manual(values = uaecols, labels = c("Arabian Gulf", "Gulf of Oman")) +
  scale_fill_manual(values = alpha(uaecols, 0.9), labels = c("Arabian Gulf", "Gulf of Oman")) +
  scale_shape_manual(values = c(8, 21:25)) +
    theme_sjb() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        legend.position = "top") +
  guides(fill = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1)) +
  xlab("Critical thermal maximum (ยบ Celsius)") +
  scale_x_continuous(limits = c(34,41), breaks = seq(34,41,1)) +
  annotation_custom(canom, xmin=33.75, xmax=35.25, ymin=6, ymax=7) +
  annotation_custom(epulc, xmin=33.75, xmax=35.25, ymin=5, ymax=6) +
  annotation_custom(event, xmin=33.75, xmax=35.25, ymin=4, ymax=5) +
  annotation_custom(hvulg, xmin=33.75, xmax=35.25, ymin=3, ymax=4) +
  annotation_custom(egutt, xmin=33.75, xmax=35.25, ymin=2, ymax=3) +
  annotation_custom(hfusc, xmin=33.75, xmax=35.25, ymin=1, ymax=2) +
  annotate("text", x = 34.5, y = 6.15, 
            label = 'italic("C. anomalus")', size = 2.5, parse = TRUE) +
    annotate("text", x = 34.5, y = 5.15, 
            label = 'italic("E. pulcher")', size = 2.5, parse = TRUE) +
    annotate("text", x = 34.5, y = 4.15, 
            label = 'italic("E. ventermaculus")', size = 2.5, parse = TRUE) +
    annotate("text", x = 34.5, y = 3.15, 
            label = 'italic("H. vulgaris")', size = 2.5, parse = TRUE) +
    annotate("text", x = 34.5, y = 2.15, 
            label = 'italic("E. guttata")', size = 2.5, parse = TRUE) +
    annotate("text", x = 34.5, y = 1.15, 
            label = 'italic("H. fuscopinna")', size = 2.5, parse = TRUE) +
    annotate("text", x = 34, y = 7.1, size = 3, label = "(b)")
  
ctmax.pred.plot




####ctmin

ctmin <- ctmin %>%
    mutate(ordervar = case_when(Tax == "CORYANOM" ~ 6,
                              Tax == "ECSEPULC" ~ 5,
                              Tax == "ENNEVENT" ~ 4,
                              Tax == "HETEVULG" ~ 3,
                              Tax == "EVIOGUTT" ~ 2,
                              TRUE ~ 1),
           taxloc = factor(interaction(Tax, Location)))

table(ctmin$taxloc)

minmod <- brm(Ctmin ~ taxloc, data = ctmin,  control = list(adapt_delta = 0.995, max_treedepth = 18), iter = 5000);beep(sound = "coin")
summary(minmod)

ctmin.pred <- ctmin %>%
  data_grid(taxloc)%>%  
  add_predicted_draws(minmod, n = 10000) %>%
  separate(taxloc, c("Tax", "Location"), remove = F) %>%
  mutate(ordervar = case_when(Tax == "CORYANOM" ~ 6,
                              Tax == "ECSEPULC" ~ 5,
                              Tax == "ENNEVENT" ~ 4,
                              Tax == "HETEVULG" ~ 3,
                              Tax == "EVIOGUTT" ~ 2,
                              TRUE ~ 1))

ctmin.pred.plot <- ggplot(data = ctmin.pred) +
  geom_halfeyeh(aes(y = ordervar, x = .prediction, fill = Location), color = "black")+
  geom_jitter(aes(x = Ctmin, y = ordervar, shape = Tax, fill = Location),
             data = ctmin, size = 1.5, color = "black", shape = 23, height = 0.1, stroke = 0.1) +
  scale_color_manual(values = uaecols, labels = c("Arabian Gulf", "Gulf of Oman")) +
  scale_fill_manual(values = alpha(uaecols, 0.9), labels = c("Arabian Gulf", "Gulf of Oman")) +
    theme_sjb() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        legend.position = "top") +
  guides(fill = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1)) +
  xlab("Critical thermal minimum (ยบ Celsius)") +
  scale_x_continuous(limits = c(9.5,16.5), breaks = seq(9,16.5,1)) +
  annotation_custom(canom, xmin=15.25, xmax=16.75, ymin=6, ymax=7) +
  annotation_custom(epulc, xmin=15.25, xmax=16.75, ymin=5, ymax=6) +
  annotation_custom(event, xmin=15.25, xmax=16.75, ymin=4, ymax=5) +
  annotation_custom(hvulg, xmin=15.25, xmax=16.75, ymin=3, ymax=4) +
  annotation_custom(egutt, xmin=15.25, xmax=16.75, ymin=2, ymax=3) +
  annotation_custom(hfusc, xmin=15.25, xmax=16.75, ymin=1, ymax=2) +
  annotate("text", x = 16, y = 6.15, 
            label = 'italic("C. anomalus")', size = 2.5, parse = TRUE) +
    annotate("text", x = 16, y = 5.15, 
            label = 'italic("E. pulcher")', size = 2.5, parse = TRUE) +
    annotate("text", x = 16, y = 4.15, 
            label = 'italic("E. ventermaculus")', size = 2.5, parse = TRUE) +
    annotate("text", x = 16, y = 3.15, 
            label = 'italic("H. vulgaris")', size = 2.5, parse = TRUE) +
    annotate("text", x = 16, y = 2.15, 
            label = 'italic("E. guttata")', size = 2.5, parse = TRUE) +
    annotate("text", x = 16, y = 1.15, 
            label = 'italic("H. fuscopinna")', size = 2.5, parse = TRUE) +
    annotate("text", x = 9.5, y = 7.1, size = 3, label = "(a)")
  
ctmin.pred.plot

#function for legend
g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

mylegend<-g_legend(ctmin.pred.plot)

ctplots <- gbm::grid.arrange( mylegend, gridExtra::arrangeGrob(ctmin.pred.plot + theme(legend.position="none"),
                         ctmax.pred.plot + theme(legend.position="none"),
                         nrow=1),
            nrow=2, heights=c(1, 12))

ggsave("Plots/Fig3_MS.png", plot = ctplots, width = 8, height = 7)
```

```{r}
# # map of study region
# 
# ####FIGURE 1B####
# library(ggmap)
# 
# world <- map_data("world")
# world_sub <- subset(world, world$long >= 50 & world$long <= 60 & world$lat >= 20 & world$lat <= 30)
# 
# country_names <- world_sub %>% group_by(region) %>% summarize(lat = mean(lat), long = mean(long))
# 
# UAEcoord <- comms[c(2,3,20,21)]
# UAEcoord_unique <- unique(UAEcoord)
# 
# middle.east <- ggplot() +
#   geom_map(data = world_sub, map = world, aes(x = long, y = lat, map_id = region), fill = "grey69", color = "grey46", lwd = 0.1) +
#   geom_point(data = UAEcoord_unique, aes(x = long, y = Lat, color = Location), size = 3, alpha = 1) +
#   xlab("Longitude") + ylab("Latitude") +
#   # scale_x_continuous(limits = c(-180, 180), breaks = seq(-180,180, 30)) +
#   # scale_y_continuous(limits = c(-60, 75), breaks = seq(-60, 75, 15)) +
#   # geom_hline(yintercept = 0, lty = 2, led = 0.1, color = "grey") +
#   annotate("text", label = "United Arab Emirates", x = 54, y = 23.5, size = 3, colour = "black") +
#   scale_color_manual(name = "Location", values = c("#00B0F0", "#ed68fc")) +
#   theme_bw() + theme(axis.title = element_text(size=10),
#                      axis.text.x = element_text(
#                        size = 10),
#                      axis.text.y = element_text(size = 10),
#                      legend.text=element_text(size=10),
#                      legend.title = element_text(size = 10, face = "bold"),
#                      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
#                      legend.position = c(0.5, 0.9),
#                      legend.direction = "horizontal",
#                      legend.background = element_rect(fill="white", color = "black", size=0.2))
# 
# middle.east
# ggsave("middle_east.pdf", plot = middle.east, width = 6, height = 5, useDingbats=FALSE)
# 
# UAElarge <- subset(world, world$long >= -10 & world$long <= 120 & world$lat >= 0 & world$lat <= 70)
# 
# middle.east.large <- ggplot() +
#   geom_map(data = UAElarge, map = world, aes(x = long, y = lat, map_id = region), fill = "grey92", color = "grey46", lwd = 0.1) +
#   xlab("Longitude") + ylab("Latitude") +
#   # scale_x_continuous(limits = c(-180, 180), breaks = seq(-180,180, 30)) +
#   # scale_y_continuous(limits = c(-60, 75), breaks = seq(-60, 75, 15)) +
#   # geom_hline(yintercept = 0, lty = 2, led = 0.1, color = "grey") +
#   scale_color_manual(name = "Location", values = c("#00B0F0", "#ed68fc")) +
#   theme_bw() + theme(axis.title = element_text(size=10),
#                      axis.text.x = element_text(
#                        size = 10),
#                      axis.text.y = element_text(size = 10),
#                      legend.text=element_text(size=10),
#                      legend.title = element_text(size = 10, face = "bold"),
#                      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
#                      legend.position = c(0.5, 0.9),
#                      legend.direction = "horizontal",
#                      legend.background = element_rect(fill="white", color = "black", size=0.2))
# 
# middle.east.large
# ggsave("middle_east_large.pdf", plot = middle.east.large, width = 6, height = 4, useDingbats=FALSE)
# 
# 
# UAEmid <- subset(world, world$long >= 30 & world$long <= 80 & world$lat >= 10 & world$lat <= 40)
# 
# middle.east.mid <- ggplot() +
#   geom_map(data = UAEmid, map = world, aes(x = long, y = lat, map_id = region), fill = "grey92", color = "grey46", lwd = 0.1) +
#   xlab("Longitude") + ylab("Latitude") +
#   # scale_x_continuous(limits = c(-180, 180), breaks = seq(-180,180, 30)) +
#   # scale_y_continuous(limits = c(-60, 75), breaks = seq(-60, 75, 15)) +
#   # geom_hline(yintercept = 0, lty = 2, led = 0.1, color = "grey") +
#   scale_color_manual(name = "Location", values = c("#00B0F0", "#ed68fc")) +
#   theme_bw() + theme(axis.title = element_text(size=10),
#                      axis.text.x = element_text(
#                        size = 10),
#                      axis.text.y = element_text(size = 10),
#                      legend.text=element_text(size=10),
#                      legend.title = element_text(size = 10, face = "bold"),
#                      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
#                      legend.position = c(0.5, 0.9),
#                      legend.direction = "horizontal",
#                      legend.background = element_rect(fill="white", color = "black", size=0.2))
# 
# middle.east.mid
# ggsave("middle_east_large.pdf", plot = middle.east.large, width = 6, height = 4, useDingbats=FALSE)
# 
# america <- subset(world, world$region == "United States of America" & world$region == "Canada")
# 
# middle.east.mid <- ggplot() +
#   geom_map(data = UAEmid, map = world, aes(x = long, y = lat, map_id = region), fill = "grey92", color = "grey46", lwd = 0.1) +
#   xlab("Longitude") + ylab("Latitude") +
#   # scale_x_continuous(limits = c(-180, 180), breaks = seq(-180,180, 30)) +
#   # scale_y_continuous(limits = c(-60, 75), breaks = seq(-60, 75, 15)) +
#   # geom_hline(yintercept = 0, lty = 2, led = 0.1, color = "grey") +
#   scale_color_manual(name = "Location", values = c("#00B0F0", "#ed68fc")) +
#   theme_bw() + theme(axis.title = element_text(size=10),
#                      axis.text.x = element_text(
#                        size = 10),
#                      axis.text.y = element_text(size = 10),
#                      legend.text=element_text(size=10),
#                      legend.title = element_text(size = 10, face = "bold"),
#                      panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
#                      legend.position = c(0.5, 0.9),
#                      legend.direction = "horizontal",
#                      legend.background = element_rect(fill="white", color = "black", size=0.2))
# 
# middle.east.mid
```

```{r DIET METABARCODING: NMDS PLOTS}
### gut content metabarcoding data

guts.meta <- read.csv(file = "Data/UAE_Metabarcoding.csv")
coi.seqs <- read.csv(file = "Data/UAE_COI.csv") %>%
  select(-c(UAE18862.1, UAE18400.1)) %>%
  filter(!species %in% c("Coryogalops anomolus", 
                         "Neopomacentrus miryae", 
                         "Ecsenius pulcher", 
                         "Belonidae sp. BOLD:AAE0217", 
                         "Eviota guttata", 
                         "Etheostoma flabellare", 
                         "Homo sapiens", 
                         "Butis gymnopomus",
                         "Dinematichthys iluocoeteoides",
                         "Oncorhynchus nerka"))

#create vector for column names 
cnames <- as.character(coi.seqs$ID)
coi.sub <- coi.seqs[c(19:104)]%>%
  #grab columns of fish gut specimens
  rownames_to_column %>% 
  gather(var, value, -rowname) %>% 
  spread(rowname, value) %>%
  set_colnames(c("ID.match", cnames)) %>%
  join(guts.meta[c("Location", "Tax", "ID.match")], by = "ID.match") %>%
  select(ID.match, Location, Tax, everything()) %>% 
  mutate(rowsum = rowSums(.[4:546])) %>%
  filter(rowsum >= 1)

coi.sub.tax <- coi.sub %>%
  filter(Tax %in% c("ENNEVENT", "CORYANOM", "ECSEPULC"))

# coi.rra <- coi.sub.tax %>%
#   select(-c(Location, Tax)) %>%
#   gather(variable, value, -ID.match) %>%
#   group_by(ID.match) %>% 
#   mutate(percentage = value/sum(value)) %>% 
#   select(-value) %>% 
#   spread(variable, percentage)



coi.pa <- coi.sub.tax %>%
  select(-c(ID.match, Location, Tax)) %>%
  mutate_all(funs(case_when(. > 0 ~ 1,
                       TRUE ~ 0))) %>%
  add_column(ID.match = coi.sub.tax$ID.match) %>%
  select(ID.match, everything())

### run mds
coi_mds <- metaMDS(coi.pa[-1], k = 3, trymax = 1000, distance = "jaccard", engine = "monoMDS", autotransform =TRUE)
coi_mds

###get values and plot in ggplot
coi.scores <- as.tibble(coi_mds$points)
coi.scores$tax <- coi.sub.tax$Tax
coi.scores$location <- coi.sub.tax$Location
coi.scores$ID.match <- coi.sub.tax$ID.match

coi.scores1 <- coi.scores %>%
  unite("taxloc", c(tax, location), remove = F)

###do permanova
coi.pa.perm <- adonis(coi.pa[-1] ~ location * tax, data = coi.scores1)
coi.pa.perm


###do simper
coi.pa.sim <- as.list(simper(coi.pa[-1], coi.scores1$taxloc))
simsum <- summary(coi.pa.sim)
top3<-lapply(simsum, `[`,1:3,)
otunames <- ldply(lapply(top3, rownames)) %>%
  gather("comparison", "ID", V1, V2, V3) %>%
  arrange(.id)

top3long <- plyr::ldply(top3, data.frame) %>%
  arrange(.id) %>%
  select(.id) %>%
  add_column(ID = otunames$ID)

OTUcoords <- as.data.frame(coi_mds$species) %>%
  add_column(ID = rownames(.))

OTUtax <- coi.seqs[c(1:10)]

top3coords <- top3long %>%
  left_join(OTUcoords, by = "ID") %>%
  left_join(OTUtax, by = "ID") %>%
  mutate(taxID = case_when(pident >= 97 ~ paste(phylum, class, order, species, sep = " | "),
                           pident >= 95 ~ paste(phylum, class, order, sep = " | "),
                           pident >= 85 ~ paste(phylum, class, sep = " | "),
                           pident >= 75 ~ paste(phylum),
                           pident < 75 ~ "Unidentified")) %>%
  mutate(oMDS1 = 0,
         oMDS2 = 0) %>%
  select(-.id) %>%
  unique(.)

# 4 is Arthropoda | Insecta (Tantytarsus)
# 6 is also Arthropoda | Insecta (Tantytarsus)
# 12 is also Arthropoda | Insecta (Tantytarsus)
###create convex hulls function
convex_hull <- function(coi.scores1) coi.scores1[chull(coi.scores1$MDS1, coi.scores1$MDS2),] 

###run convex hulls on habitats
fish_hulls <- ddply(coi.scores1, "taxloc", convex_hull)

# ### set colors
taxloccols <- c("olivedrab4", "olivedrab2", "cyan4", "cyan2", "darkorchid4", "darkorchid2")

###plot mds results
# plot one species name
mds.pa.coi.loc <- ggplot(coi.scores1, aes(x = MDS1, y = MDS2)) +
  #overlay convex hulls
  geom_polygon(data = fish_hulls, aes(x = MDS1, y = MDS2,
                                         color = taxloc,
                                         group = taxloc), fill = "grey69",
               alpha = 0.1, lty = 1, lwd = 0.1) +
  # stat_ellipse(data = fish.scores1, aes(x = MDS1, y = MDS2, group = species),
  #              alpha = 1, lty = 1, lwd = 0.3, level = 0.50) +
  #overlay point
  geom_point(size = 2, aes(color = taxloc, group = taxloc, shape = location)) +
  theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") +
  scale_y_continuous(limits = c(-1.4,1.1), breaks = seq(-1,1,0.5)) +
  scale_x_continuous(limits = c(-1.1,1.6), breaks = seq(-1,1,0.5)) +
  scale_color_manual(values = taxloccols) +
  scale_fill_manual(values = taxloccols)

mds.pa.coi.loc

mds.top3.coi.loc <- ggplot(top3coords, aes(x = MDS1, y = MDS2)) +
  geom_segment(data = top3coords, mapping = aes(xend = oMDS1, yend = oMDS2), lwd = 0.2, lty = 2) +
  geom_point(size = 3, shape = 18) +
    geom_label_repel(aes(label = taxID), size = 2) +
    theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") +
    scale_y_continuous(limits = c(-1.4,1.1), breaks = seq(-1,1,0.5)) +
  scale_x_continuous(limits = c(-1.1,1.6), breaks = seq(-1,1,0.5)) 
mds.top3.coi.loc

mds.coi.loc.vec <- ggarrange(mds.pa.coi.loc, mds.top3.coi.loc, ncol = 1, nrow = 2)

ggsave("Plots/mds.pa.coi.loc.pdf", mds.coi.loc.vec, width = 7, height = 10, useDingbats = FALSE)

### bring in other taxa
coi.sub.taxloc <- coi.sub

# coi.rra <- coi.sub.tax %>%
#   select(-c(Location, Tax)) %>%
#   gather(variable, value, -ID.match) %>%
#   group_by(ID.match) %>% 
#   mutate(percentage = value/sum(value)) %>% 
#   select(-value) %>% 
#   spread(variable, percentage)



coi.pa.taxloc <- coi.sub.taxloc %>%
  select(-c(ID.match, Location, Tax)) %>%
  mutate_all(funs(case_when(. > 0 ~ 1,
                       TRUE ~ 0))) %>%
  add_column(ID.match = coi.sub.taxloc$ID.match) %>%
  select(ID.match, everything())

### run mds
coi.mds.taxloc <- metaMDS(coi.pa.taxloc[-1], k = 3, trymax = 1000, distance = "jaccard", engine = "monoMDS", autotransform =TRUE)
coi.mds.taxloc

###get values and plot in ggplot
coi.scores.taxloc <- as.tibble(coi.mds.taxloc$points)
coi.scores.taxloc$tax <- coi.sub.taxloc$Tax
coi.scores.taxloc$location <- coi.sub.taxloc$Location
coi.scores.taxloc$ID.match <- coi.sub.taxloc$ID.match

coi.scores.taxloc1 <- coi.scores.taxloc %>%
  unite("taxloc", c(tax, location), remove = F)


###do permanova
coi.pa.perm.taxloc <- adonis(coi.pa.taxloc[-1] ~ location * tax, data = coi.scores.taxloc1)
coi.pa.perm.taxloc

###do simper
coi.pa.sim.taxloc <- as.list(simper(coi.pa.taxloc[-1], coi.scores.taxloc1$taxloc))
simsum.taxloc <- summary(coi.pa.sim.taxloc)
top3.taxloc<-lapply(simsum.taxloc, `[`,1:3,)
otunames <- ldply(lapply(top3.taxloc, rownames)) %>%
  gather("comparison", "ID", V1, V2, V3) %>%
  arrange(.id)

top3long.taxloc <- plyr::ldply(top3.taxloc, data.frame) %>%
  arrange(.id) %>%
  select(.id) %>%
  add_column(ID = otunames$ID)

OTUcoords.taxloc <- as.data.frame(coi.mds.taxloc$species) %>%
  add_column(ID = rownames(.))

OTUtax <- coi.seqs[c(1:10)]

top3coords.taxloc <- top3long %>%
  left_join(OTUcoords.taxloc, by = "ID") %>%
  left_join(OTUtax, by = "ID") %>%
  mutate(taxID = case_when(pident >= 97 ~ paste(phylum, class, order, species, sep = " | "),
                           pident >= 95 ~ paste(phylum, class, order, sep = " | "),
                           pident >= 85 ~ paste(phylum, class, sep = " | "),
                           pident >= 75 ~ paste(phylum),
                           pident < 75 ~ "Unidentified")) %>%
  mutate(oMDS1 = 0,
         oMDS2 = 0) %>%
  select(-.id) %>%
  unique(.) %>%
  replace_na(list(taxID = "Chordata | Actinpterygii | Blenniiformes | Salarias fasciatus"))
#7 is arthropoda tantytarsus again
#12 is Salarias fasciatus

###create convex hulls function
convex_hull <- function(coi.scores.taxloc1) coi.scores.taxloc1[chull(coi.scores.taxloc1$MDS1, coi.scores.taxloc1$MDS2),] 

###run convex hulls on habitats
fish.hulls.taxloc <- ddply(coi.scores.taxloc1, "taxloc", convex_hull)

# ### set colors
taxcols <- c("gold2", "olivedrab4", "olivedrab2", "cyan4", "cyan2", "darkorchid4", "darkorchid2", "lightpink1", "royalblue2")

###plot mds results
# plot one species name
mds.pa.coi.taxloc <- ggplot(coi.scores.taxloc1, aes(x = MDS1, y = MDS2)) +
  #overlay convex hulls
  geom_polygon(data = fish.hulls.taxloc, aes(x = MDS1, y = MDS2,
                                         color = taxloc,
                                         group = taxloc), fill = "grey69",
               alpha = 0.1, lty = 1, lwd = 0.1) +
  # stat_ellipse(data = fish.scores1, aes(x = MDS1, y = MDS2, group = species),
  #              alpha = 1, lty = 1, lwd = 0.3, level = 0.50) +
  #overlay point
  geom_point(size = 2, aes(color = taxloc, group = taxloc, shape = location)) +
  theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none")+
  scale_y_continuous(limits = c(-1.4,1.3), breaks = seq(-1,1,0.5)) +
  scale_x_continuous(limits = c(-1.1,1.6), breaks = seq(-1,1,0.5)) +
  scale_color_manual(values = taxcols) +
  scale_fill_manual(values = taxcols)

mds.pa.coi.taxloc

mds.top3.coi.taxloc <- ggplot(top3coords.taxloc, aes(x = MDS1, y = MDS2)) +
  geom_segment(mapping = aes(xend = oMDS1, yend = oMDS2), lwd = 0.2, lty = 2) +
  geom_point(size = 3, shape = 18) +
    geom_label_repel(aes(label = taxID), size = 2) +
    theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") +
  scale_y_continuous(limits = c(-1.4,1.3), breaks = seq(-1,1,0.5)) +
  scale_x_continuous(limits = c(-1.1,1.6), breaks = seq(-1,1,0.5)) 
mds.top3.coi.taxloc

mds.coi.taxloc.vec <- ggarrange(mds.pa.coi.taxloc, mds.top3.coi.taxloc, ncol = 1, nrow = 2)

ggsave("mds.pa.coi.taxloc.pdf", mds.coi.loc.vec, width = 10, height = 8, useDingbats = FALSE)
# 
# ### do taxa in Gulf of Oman only
# coi.sub.tax <- coi.sub %>%
#     filter(Location == "GoO")
# 
# # coi.rra <- coi.sub.tax %>%
# #   select(-c(Location, Tax)) %>%
# #   gather(variable, value, -ID.match) %>%
# #   group_by(ID.match) %>% 
# #   mutate(percentage = value/sum(value)) %>% 
# #   select(-value) %>% 
# #   spread(variable, percentage)
# 
# coi.pa.tax <- coi.sub.tax %>%
#   select(-c(ID.match, Location, Tax)) %>%
#   mutate_all(funs(case_when(. > 0 ~ 1,
#                        TRUE ~ 0))) %>%
#   add_column(ID.match = coi.sub.tax$ID.match) %>%
#   select(ID.match, everything())
# 
# ### run mds
# coi.mds.tax <- metaMDS(coi.pa.tax[-1], k = 3, trymax = 2000, distance = "jaccard", engine = "monoMDS", autotransform =TRUE)
# coi.mds.tax
# 
# ###get values and plot in ggplot
# coi.scores.tax <- as.tibble(coi.mds.tax$points)
# coi.scores.tax$tax <- coi.sub.tax$Tax
# coi.scores.tax$location <- coi.sub.tax$Location
# coi.scores.tax$ID.match <- coi.sub.tax$ID.match
# 
# coi.scores.tax1 <- coi.scores.tax %>%
#   unite("taxloc", c(tax, location), remove = F)
# 
# 
# ###create convex hulls function
# convex_hull <- function(coi.scores.tax1) coi.scores.tax1[chull(coi.scores.tax1$MDS1, coi.scores.tax1$MDS2),] 
# 
# ###run convex hulls on habitats
# fish.hulls.tax <- ddply(coi.scores.tax, "tax", convex_hull)
# 
# # ### set colors
# taxonlycols <- c("gold2", "olivedrab2", "cyan2", "darkorchid2", "lightpink1", "royalblue2")
# 
# ###plot mds results
# # plot one species name
# mds.pa.coi.tax <- ggplot(coi.scores.tax1, aes(x = MDS1, y = MDS2)) +
#   #overlay convex hulls
#   geom_polygon(data = fish.hulls.tax, aes(x = MDS1, y = MDS2,
#                                          color = tax,
#                                          group = tax), fill = "grey69",
#                alpha = 0.1, lty = 1, lwd = 0.1) +
#   # stat_ellipse(data = fish.scores1, aes(x = MDS1, y = MDS2, group = species),
#   #              alpha = 1, lty = 1, lwd = 0.3, level = 0.50) +
#   #overlay point
#   geom_point(size = 2, aes(color = tax, group = tax), shape = 17) +
#   theme_bw() + theme(panel.grid.major = element_blank(), 
#                      panel.grid.minor = element_blank(),
#                      axis.title = element_text(size=14),
#                      axis.text.x = element_text(size = 14),
#                      axis.text.y = element_text(size = 14),
#                      legend.position = "none") +
#   #   scale_y_continuous(limits = c(-1.2,1.2), breaks = seq(-1,1,0.5)) +
#   # scale_x_continuous(limits = c(-1.2,1.4), breaks = seq(-1,1,0.5)) +
#   scale_color_manual(values = taxonlycols) +
#   scale_fill_manual(values = taxonlycols)

mds.coi.tax.vec <- ggarrange(mds.pa.coi.tax, mds.top3.coi.taxloc, ncol = 1, nrow = 2)

ggsave("mds.coi.tax.vec", mds.pa.coi.tax, width = 7, height = 10, useDingbats = FALSE)

coi.plots <- ggarrange(mds.coi.loc.vec, mds.coi.taxloc.vec, nrow = 1, ncol = 2)
coi.plots
ggsave("mds.coi.vec.pdf", coi.plots, width = 12, height = 12, useDingbats = FALSE)



###23S data
seqs23s <- read.csv(file = "Data/UAE_23S.csv") %>%
  select(-c(UAE18862.1, UAE18400.1))
#create vector for column names 
cnames <- as.character(seqs23s$ESV)
sub23s <- seqs23s %>%
  #grab columns of fish gut specimens
  select(., contains("UAE18")) %>%
  rownames_to_column %>% 
  gather(var, value, -rowname) %>% 
  spread(rowname, value) %>%
  set_colnames(c("ID.match", cnames)) %>%
  join(guts.meta[c("Location", "Tax", "ID.match")], by = "ID.match") %>%
  select(ID.match, Location, Tax, everything()) %>% 
  mutate(rowsum = rowSums(.[4:3009]))

sub23s.loc <- sub23s %>%
  filter(Tax %in% c("ENNEVENT", "CORYANOM", "ECSEPULC"))

# coi.rra <- coi.sub.tax %>%
#   select(-c(Location, Tax)) %>%
#   gather(variable, value, -ID.match) %>%
#   group_by(ID.match) %>% 
#   mutate(percentage = value/sum(value)) %>% 
#   select(-value) %>% 
#   spread(variable, percentage)
# 


pa23s.loc <- sub23s.loc %>%
  select(-c(ID.match, Location, Tax)) %>%
  mutate_all(funs(case_when(. > 0 ~ 1,
                       TRUE ~ 0))) %>%
  add_column(ID.match = sub23s.loc$ID.match) %>%
  select(ID.match, everything())

### run mds
mds23s.loc <- metaMDS(pa23s.loc[-1], k = 3, trymax = 1000, distance = "jaccard", engine = "monoMDS", autotransform =TRUE)

###get values and plot in ggplot
scores23s.loc <- as.tibble(mds23s.loc$points)
scores23s.loc$tax <- sub23s.loc$Tax
scores23s.loc$location <- sub23s.loc$Location
scores23s.loc$ID.match <- sub23s.loc$ID.match

scores23s.loc1 <- scores23s.loc %>%
  unite("taxloc", c(tax, location), remove = F)


###do permanova
perm.23.loc <- adonis(pa23s.loc[-1] ~ location * tax, data = scores23s.loc1)
perm.23.loc

###do simper
pa.sim.23s.loc <- as.list(simper(pa23s.loc[-1], scores23s.loc1$taxloc))
simsum.23sloc <- summary(pa.sim.23s.loc)
top3.23s.loc<-lapply(simsum.23sloc, `[`,1,)
esvnames <- ldply(lapply(top3.23s.loc, rownames)) %>%
  gather("comparison", "ESV", V1) %>%
  arrange(.id)

top3long.23s.loc <- plyr::ldply(top3.23s.loc, data.frame) %>%
  arrange(.id) %>%
  select(.id) %>%
  add_column(ESV = esvnames$ESV)

ESVcoords.23s.loc <- as.data.frame(mds23s.loc$species) %>%
  add_column(ESV = rownames(.))

ESVtax <- seqs23s[c(1:9)]

top3coords.23s.loc <- top3long.23s.loc %>%
  left_join(ESVcoords.23s.loc, by = "ESV") %>%
  left_join(ESVtax, by = "ESV") %>%
  mutate(taxID = case_when(id >= 97 ~ paste(Phylum, Order, Species, sep = " | "),
                           id >= 95 ~ paste(Phylum, Order, sep = " | "),
                           id >= 85 ~ paste(Phylum, Order, sep = " | "),
                           id >= 75 ~ paste(Phylum),
                           id < 75 ~ "Unidentified")) %>%
  mutate(oMDS1 = 0,
         oMDS2 = 0) %>%
  select(-.id) %>%
  distinct(taxID, MDS1, MDS2, oMDS1, oMDS2) 


###create convex hulls function
convex_hull <- function(scores23s.loc1) scores23s.loc1[chull(scores23s.loc1$MDS1, scores23s.loc1$MDS2),] 

###run convex hulls on habitats
fish.hulls23s.loc <- ddply(scores23s.loc1, "taxloc", convex_hull)

# ### set colors
taxloccols <- c("olivedrab4", "olivedrab2", "cyan4", "cyan2", "darkorchid4", "darkorchid2")

###plot mds results
# plot one species name
mds.pa.23s.loc <- ggplot(scores23s.loc1, aes(x = MDS1, y = MDS2)) +
  #overlay convex hulls
  geom_polygon(data = fish.hulls23s.loc, aes(x = MDS1, y = MDS2,
                                         color = taxloc,
                                         group = taxloc), fill = "grey69",
               alpha = 0.1, lty = 1, lwd = 0.1) +
  # stat_ellipse(data = fish.scores1, aes(x = MDS1, y = MDS2, group = species),
  #              alpha = 1, lty = 1, lwd = 0.3, level = 0.50) +
  #overlay point
  geom_point(size = 2, aes(color = taxloc, group = taxloc, shape = location)) +
  theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") +
  scale_y_continuous(limits = c(-2.5,1.2), breaks = seq(-2,1,0.5)) +
  scale_x_continuous(limits = c(-1.8,1.2), breaks = seq(-2,1,0.5)) +
  scale_color_manual(values = taxloccols) +
  scale_fill_manual(values = taxloccols)

mds.pa.23s.loc
ggsave("mds.pa.23s.loc.pdf", mds.pa.23s.loc, width = 10, height = 8, useDingbats = FALSE)

mds.top3.23s.loc <- ggplot(top3coords.23s.loc, aes(x = MDS1, y = MDS2)) +
  geom_segment(mapping = aes(xend = oMDS1, yend = oMDS2), lwd = 0.2, lty = 2) +
  geom_point(size = 3, shape = 18) +
    geom_label_repel(aes(label = taxID), size = 1.5, segment.size = 0.2) +
    theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") + 
  scale_y_continuous(limits = c(-2.5,1.2), breaks = seq(-2,1,0.5)) +
  scale_x_continuous(limits = c(-1.8,1.2), breaks = seq(-2,1,0.5))
mds.top3.23s.loc

mds.23s.loc.vec <- ggarrange(mds.pa.23s.loc, mds.top3.23s.loc, ncol = 1, nrow = 2)
mds.23s.loc.vec
ggsave("mds.23s.loc.vec.pdf", mds.23s.loc.vec, width = 7, height = 10, useDingbats = FALSE)




### try bringing in the other taxa
sub23s.taxloc <- sub23s 

pa23s.taxloc <- sub23s.taxloc %>%
  select(-c(ID.match, Location, Tax)) %>%
  mutate_all(funs(case_when(. > 0 ~ 1,
                       TRUE ~ 0))) %>%
  add_column(ID.match = sub23s.taxloc$ID.match) %>%
  select(ID.match, everything())

### run mds
mds23s.taxloc <- metaMDS(pa23s.taxloc[-1], k = 3, trymax = 1000, distance = "jaccard", engine = "monoMDS", autotransform =TRUE)

###get values and plot in ggplot
scores23s.taxloc <- as.tibble(mds23s.taxloc$points)
scores23s.taxloc$tax <- sub23s.taxloc$Tax
scores23s.taxloc$location <- sub23s.taxloc$Location
scores23s.taxloc$ID.match <- sub23s.taxloc$ID.match

scores23s1.taxloc <- scores23s.taxloc %>%
   unite("taxloc", c(tax, location), remove = F)

###do permanova
perm.23.taxloc <- adonis(pa23s.taxloc[-1] ~ location * tax, data = scores23s1.taxloc)
perm.23.taxloc

###do simper
pa.sim.23s.taxloc <- as.list(simper(pa23s.taxloc[-1], scores23s1.taxloc$taxloc))
simsum.23staxloc <- summary(pa.sim.23s.taxloc)
top3.23s.taxloc<-lapply(simsum.23staxloc, `[`,1,)
esvnames <- ldply(lapply(top3.23s.taxloc, rownames)) %>%
  gather("comparison", "ESV", V1) %>%
  arrange(.id)

top3long.23s.taxloc <- plyr::ldply(top3.23s.taxloc, data.frame) %>%
  arrange(.id) %>%
  select(.id) %>%
  add_column(ESV = esvnames$ESV)

ESVcoords.23s.taxloc <- as.data.frame(mds23s.taxloc$species) %>%
  add_column(ESV = rownames(.))

ESVtax <- seqs23s[c(1:9)]

top3coords.23s.taxloc <- top3long.23s.taxloc %>%
  left_join(ESVcoords.23s.taxloc, by = "ESV") %>%
  left_join(ESVtax, by = "ESV") %>%
  mutate(taxID = case_when(id >= 97 ~ paste(Phylum, Order, Species, sep = " | "),
                           id >= 95 ~ paste(Phylum, Order, sep = " | "),
                           id >= 85 ~ paste(Phylum, Order, sep = " | "),
                           id >= 75 ~ paste(Phylum),
                           id < 75 ~ "Unidentified")) %>%
  mutate(oMDS1 = 0,
         oMDS2 = 0) %>%
  select(-.id) %>%
  distinct(taxID, MDS1, MDS2, oMDS1, oMDS2) 



###create convex hulls function
convex_hull <- function(scores23s1.taxloc) scores23s1.taxloc[chull(scores23s1.taxloc$MDS1, scores23s1.taxloc$MDS2),] 

###run convex hulls on habitats
fish.hulls23s.taxloc <- ddply(scores23s1.taxloc, "taxloc", convex_hull)

# ### set colors
taxcols <- c("gold2", "olivedrab4", "olivedrab2", "cyan4", "cyan2", "darkorchid4", "darkorchid2", "lightpink1", "royalblue2")

###plot mds results
# plot one species name
mds.pa.23s.taxloc <- ggplot(scores23s1.taxloc, aes(x = MDS1, y = MDS2)) +
  #overlay convex hulls
  geom_polygon(data = fish.hulls23s.taxloc, aes(x = MDS1, y = MDS2,
                                         color = taxloc,
                                         group = taxloc), fill = "grey69",
               alpha = 0.1, lty = 1, lwd = 0.1) +
  # stat_ellipse(data = fish.scores1, aes(x = MDS1, y = MDS2, group = species),
  #              alpha = 1, lty = 1, lwd = 0.3, level = 0.50) +
  #overlay point
  geom_point(size = 2, aes(color = taxloc, group = taxloc, shape = location)) +
  theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") +
  scale_y_continuous(limits = c(-2.1,1.3), breaks = seq(-2,1,0.5)) +
  scale_x_continuous(limits = c(-2.3,1), breaks = seq(-2,1,0.5)) +
  scale_color_manual(values = taxcols) +
  scale_fill_manual(values = taxcols)

mds.pa.23s.taxloc
ggsave("mds.pa.23s.taxloc.pdf", mds.pa.23s.taxloc, width = 10, height = 8, useDingbats = FALSE)


mds.top3.23s.taxloc <- ggplot(top3coords.23s.taxloc, aes(x = MDS1, y = MDS2)) +
  geom_segment(mapping = aes(xend = oMDS1, yend = oMDS2), lwd = 0.2, lty = 2) +
  geom_point(size = 3, shape = 18) +
    geom_label_repel(aes(label = taxID), size = 1.5, segment.size = 0.2) +
    theme_bw() + theme(panel.grid.major = element_blank(), 
                     panel.grid.minor = element_blank(),
                     axis.title = element_text(size=10),
                     axis.text.x = element_text(size = 10),
                     axis.text.y = element_text(size = 10),
                     legend.position = "none") +
  scale_y_continuous(limits = c(-2.1,1.3), breaks = seq(-2,1,0.5)) +
  scale_x_continuous(limits = c(-2.3,1), breaks = seq(-2,1,0.5)) 
mds.top3.23s.taxloc

mds.23s.taxloc.vec <- ggarrange(mds.pa.23s.taxloc, mds.top3.23s.taxloc, ncol = 1, nrow = 2)
mds.23s.taxloc.vec
ggsave("mds.23s.loc.vec.pdf", mds.23s.loc.vec, width = 7, height = 10, useDingbats = FALSE)

plots23s <- ggarrange(mds.23s.loc.vec, mds.23s.taxloc.vec, nrow = 1, ncol = 2)

ggsave("plots23svectors.pdf", plots23s, width = 12, height = 12, useDingbats = FALSE)


#######################
#######################
#######################network
meta.coi <- coi.sub.taxloc[c(1:3)]
network.coi <- coi.pa %>%
  select(-rowsum) %>%
  pivot_longer(cols = 2:547, names_to = "ID") %>%
  filter(value > 0) %>%
  left_join(meta.coi[1:3], by = "ID.match") %>%
  group_by(ID, Location, Tax) %>%
  summarize(value = sum(value))

table(network.coi$ID, network.coi$Location)

share.color <- network.coi %>%
  select(ID, Location) %>%
  distinct() 

shared <- share.color %>%
  mutate(indicator = 1) %>%
  group_by(ID) %>%
  summarize(shared = sum(indicator)) %>%
  mutate(sharedornot = case_when(shared == 1 ~ "unique",
                                 TRUE ~ "Shared")) %>%
  right_join(share.color) %>%
  mutate(share.color = case_when(sharedornot == "unique" ~ paste(Location),
                                 TRUE ~ paste(sharedornot)))
  
network.coi.colored <- network.coi %>%
  left_join(shared, by = "ID") %>%
  mutate(taxloc = interaction(Tax, Location.y))

uaecols.network <- c(uaecols, "grey46")

network.plot.coi <- ggplot(data = network.coi.colored) +
  geom_net(layout.alg = "fruchtermanreingold", aes(from_id = ID, to_id = taxloc, colour = share.color, shape = Tax),
  lwd=2, labelon = F, alpha = 0.8, ealpha = 0.1, arrowsize = 0.1, linewidth = 0.05, 
  vjust = 0.5, hjust = 0.5) +
  # labelcolour = cfnet2$lcolour) +
  theme_net() +
  # scale_colour_manual(values = c("deepskyblue", "navy", "mediumspringgreen", "green4")) +
  scale_color_manual(values = uaecols.network) +
  scale_shape_manual(values = c(3:5)) +
  theme(legend.position = "right")
network.plot.coi


cfstat <- graph_from_data_frame(network.coi)

###get network community characteristics
ed <- edge_density(cfstat, loops=F)

net.sym <- as.undirected(cfstat, mode= "collapse", edge.attr.comb=list(weight="sum", "ignore"))

ceb <- cluster_edge_betweenness(net.sym) 
memb <- membership(ceb)
modul <- modularity(ceb)
############

meta.23s <- sub23s.loc[c(1:3)]
network.23s <- pa23s.loc %>%
  select(-rowsum) %>%
  pivot_longer(cols = 2:3007, names_to = "ID") %>%
  filter(value > 0) %>%
  left_join(meta.23s[1:3], by = "ID.match") %>%
  group_by(ID, Location, Tax) %>%
  summarize(value = sum(value))

share.color.23s <- network.23s %>%
  select(ID, Location) %>%
  distinct() 

shared.23s <- share.color.23s %>%
  mutate(indicator = 1) %>%
  group_by(ID) %>%
  summarize(shared = sum(indicator)) %>%
  mutate(sharedornot = case_when(shared == 1 ~ "unique",
                                 TRUE ~ "Shared")) %>%
  right_join(share.color.23s) %>%
  mutate(share.color = case_when(sharedornot == "unique" ~ paste(Location),
                                 TRUE ~ paste(sharedornot)))
  
network.23s.colored <- network.23s %>%
  left_join(shared, by = "ID") %>%
  mutate(taxloc = interaction(Tax, Location.y))

uaecols.network <- c(uaecols, "grey46")

network.plot.23s <- ggplot(data = network.23s.colored) +
  geom_net(layout.alg = "fruchtermanreingold", aes(from_id = ID, to_id = taxloc, colour = share.color, shape = Tax),
  lwd = 2, labelon = F, alpha = 0.8, ealpha = 0.1, arrowsize = 0.1, linewidth = 0.05,
  vjust = 0.5, hjust = 0.5, repel = TRUE) +
  # labelcolour = cfnet2$lcolour) +
  theme_net() +
  # scale_colour_manual(values = c("deepskyblue", "navy", "mediumspringgreen", "green4")) +
  scale_color_manual(values = uaecols.network) +
  scale_shape_manual(values = c(3:5)) +
  theme(legend.position = "right")
network.plot.23s

cfstat23s <- graph_from_data_frame(network.23s)

###get network community characteristics
ed23s <- edge_density(cfstat23s, loops=F)

net.sym23s <- as.undirected(cfstat23s, mode= "collapse", edge.attr.comb=list(weight="sum", "ignore"))

ceb23s <- cluster_edge_betweenness(net.sym23s) 
memb23s <- membership(ceb23s)
modul23s <- modularity(ceb23s)

networklegend<-g_legend(network.plot.23s)

networkplots <- gbm::grid.arrange(mylegend, gridExtra::arrangeGrob(network.plot.coi + theme(legend.position="none"),
                         network.plot.23s + theme(legend.position="none"),
                         nrow=2),
            nrow=2, heights=c(1, 12))

ggsave("Plots/Fig5_MS.pdf", plot = networkplots, width = 6, height = 8, useDingbats=FALSE)

### do taxa in GoO only
# sub23s.tax <- sub23s %>%
#   filter(Location == "GoO")
# 
# pa23s.tax <- sub23s.tax %>%
#   select(-c(ID.match, Location, Tax)) %>%
#   mutate_all(funs(case_when(. > 0 ~ 1,
#                        TRUE ~ 0))) %>%
#   add_column(ID.match = sub23s.tax$ID.match) %>%
#   select(ID.match, everything())
# 
# ### run mds
# mds23s.tax <- metaMDS(pa23s.tax[-1], k = 3, trymax = 1000, distance = "jaccard", engine = "monoMDS", autotransform =TRUE)
# 
# ###get values and plot in ggplot
# scores23s.tax <- as.tibble(mds23s.tax$points)
# scores23s.tax$tax <- sub23s.tax$Tax
# scores23s.tax$location <- sub23s.tax$Location
# scores23s.tax$ID.match <- sub23s.tax$ID.match
# 
# scores23s1.tax <- scores23s.tax %>%
#    unite("taxloc", c(tax, location), remove = F)
# 
# 
# ###create convex hulls function
# convex_hull <- function(scores23s1.tax) scores23s1.tax[chull(scores23s1.tax$MDS1, scores23s1.tax$MDS2),] 
# 
# ###run convex hulls on habitats
# fish.hulls23s.tax <- ddply(scores23s1.tax, "tax", convex_hull)
# 
# # ### set colors
# taxonlycols <- c("gold2", "olivedrab2", "cyan2", "darkorchid2", "lightpink1", "royalblue2")
# 
# ###plot mds results
# # plot one species name
# mds.pa.23s.tax <- ggplot(scores23s1.tax, aes(x = MDS1, y = MDS2)) +
#   #overlay convex hulls
#   geom_polygon(data = fish.hulls23s.tax, aes(x = MDS1, y = MDS2,
#                                          color = tax,
#                                          group = tax), fill = "grey69",
#                alpha = 0.1, lty = 1, lwd = 0.1) +
#   # stat_ellipse(data = fish.scores1, aes(x = MDS1, y = MDS2, group = species),
#   #              alpha = 1, lty = 1, lwd = 0.3, level = 0.50) +
#   #overlay point
#   geom_point(size = 2, aes(color = tax, group = tax), shape = 17) +
#   theme_bw() + theme(panel.grid.major = element_blank(), 
#                      panel.grid.minor = element_blank(),
#                      axis.title = element_text(size=10),
#                      axis.text.x = element_text(size = 10),
#                      axis.text.y = element_text(size = 10),
#                      legend.position = "none") +
#   #   scale_y_continuous(limits = c(-1.2,1.2), breaks = seq(-1,1,0.5)) +
#   # scale_x_continuous(limits = c(-1.2,1.4), breaks = seq(-1,1,0.5)) +
#   scale_color_manual(values = taxonlycols) +
#   scale_fill_manual(values = taxonlycols)
# 
# mds.pa.23s.tax
# ggsave("mds.pa.23s.tax.pdf", mds.pa.23s.tax, width = 10, height = 8, useDingbats = FALSE)
# 
# plots23s <- ggarrange(mds.pa.23s.loc, mds.pa.23s.taxloc, mds.pa.23s.tax, nrow = 1, ncol = 3)
# plots23s
# 
# ggsave("plots23s.pdf", plots23s, width = 10, height = 8, useDingbats = FALSE)
```

```{r OTU/ESV DIVESRITY: RAREFACTION}
# #coi otus and sequences
# preydiv.coi <- coi.sub %>%
#   select(-rowsum) %>%
#   pivot_longer(OTU_8:OTU_394, names_to = "OTUs") %>%
#   mutate(presabs = case_when(value > 0 ~ 1,
#                               TRUE ~ 0)) %>%
#   arrange(-value)
#   # group_by(ID.match, Location, Tax) %>%
#   # summarize(nb.otu.coi = sum(presabs),
#   #           nb.seq.coi = sum(value))
# preydiv.coi
# 
# #23s esvs and sequences
# preydiv.23s <-   sub23s %>%
#   select(-rowsum) %>%
#   pivot_longer(ESV_000034:ESV_036113, names_to = "ESVs") %>%
#   mutate(presabs = case_when(value > 0 ~ 1,
#                               TRUE ~ 0)) %>%
#   group_by(ID.match, Location, Tax) %>%
#   summarize(nb.esv.23s = sum(presabs),
#             nb.seq.23s = sum(value))
# preydiv.23s
# 
# preydiv.allprim <- inner_join(preydiv.coi, preydiv.23s, by = c("ID.match", "Location", "Tax")) %>%
#   mutate(ratio_tax = nb.otu.coi/nb.esv.23s,
#          ratio_seq = nb.seq.coi/nb.seq.23s,
#          tax_unit_sum = nb.otu.coi + nb.esv.23s) %>%
#   group_by(Location, Tax) %>%
#   summarize(mean_nbotu = mean(nb.otu.coi),
#             mean_nbesv = mean(nb.esv.23s),
#             mean_nbtotal = mean(tax_unit_sum),
#             mean_seq_coi = mean(nb.seq.coi),
#             mean_seq_23s = mean(nb.seq.23s),
#             mean_ratio_tax = mean(ratio_tax),
#             mean_ratio_seq = mean(ratio_seq)) %>%
#   arrange(Tax)
# preydiv.allprim


# 
# ### diatoms
# coi.seqs.bac <- coi.seqs %>%
#   filter(phylum == "Bacillariophyta")
# cnames.bac <- as.character(coi.seqs.bac$ID)
# coi.sub.bac <- coi.seqs.bac[c(19:104)]%>%
#   #grab columns of fish gut specimens
#   rownames_to_column %>% 
#   gather(var, value, -rowname) %>% 
#   spread(rowname, value) %>%
#   set_colnames(c("ID.match", cnames.bac)) %>%
#   join(guts.meta[c("Location", "Tax", "ID.match")], by = "ID.match") %>%
#   select(ID.match, Location, Tax, everything())
# 
# preydiv.coi.bac <- coi.sub.bac %>%
#   pivot_longer(OTU_8:OTU_395, names_to = "OTUs") %>%
#   mutate(presabs = case_when(value > 0 ~ 1,
#                               TRUE ~ 0)) %>%
#   group_by(ID.match, Location, Tax) %>%
#   summarize(nb.otu.coi = sum(presabs),
#             nb.seq.coi = sum(value))
# preydiv.coi.bac

# ###
# ###23S data
# bac.23s <- seqs23s %>%
#   filter(Phylum == "Bacillariophyta")
# cnames <- as.character(bac.23s$ESV)
# sub23s.bac <- bac.23s %>%
#   #grab columns of fish gut specimens
#   select(., contains("UAE18")) %>%
# #   rownames_to_column %>% 
# #   gather(var, value, -rowname) %>% 
# #   spread(rowname, value) %>%
# #   set_colnames(c("ID.match", cnames)) %>%
# #   join(guts.meta[c("Location", "Tax", "ID.match")], by = "ID.match") 
# # 
# # preydiv.23s.bac <- sub23s.bac %>%
# #   pivot_longer(ESV_005478:ESV_036113, names_to = "ESVs") %>%
# #   mutate(presabs = case_when(value > 0 ~ 1,
# #                               TRUE ~ 0)) %>%
# #   group_by(ID.match, Location, Tax) %>%
# #   summarize(nb.esv.23s = sum(presabs),
# #             nb.seq.23s = sum(value))
# # preydiv.23s.bac
# # 
# # preydiv.allprim.bac <- inner_join(preydiv.coi.bac, preydiv.23s.bac, by = c("ID.match", "Location", "Tax")) %>%
# #   mutate(ratio_tax = nb.otu.coi/nb.esv.23s,
# #          ratio_seq = nb.seq.coi/nb.seq.23s,
# #          tax_unit_sum = nb.otu.coi + nb.esv.23s) %>%
# #   group_by(Location, Tax) %>%
# #   summarize(mean_nbotu = mean(nb.otu.coi),
# #             mean_nbesv = mean(nb.esv.23s),
# #             mean_nbtotal = mean(tax_unit_sum),
# #             mean_seq_coi = mean(nb.seq.coi),
# #             mean_seq_23s = mean(nb.seq.23s),
# #             mean_ratio_tax = mean(ratio_tax),
# #             mean_ratio_seq = mean(ratio_seq)) %>%
# #   arrange(Tax)
# # preydiv.allprim.bac
# 
# 
# ####all but diatoms
# coi.seqs.nobac <- coi.seqs %>%
#   filter(phylum != "Bacillariophyta")
# cnames.nobac <- as.character(coi.seqs.nobac$ID)
# coi.sub.nobac <- coi.seqs.nobac[c(19:104)]%>%
#   #grab columns of fish gut specimens
#   rownames_to_column %>% 
#   gather(var, value, -rowname) %>% 
#   spread(rowname, value) %>%
#   set_colnames(c("ID.match", cnames.nobac)) %>%
#   join(guts.meta[c("Location", "Tax", "ID.match")], by = "ID.match") %>%
#   select(ID.match, Location, Tax, everything())
# 
# preydiv.coi.nobac <- coi.sub.nobac %>%
#   pivot_longer(OTU_11:OTU_394, names_to = "OTUs") %>%
#   mutate(presabs = case_when(value > 0 ~ 1,
#                               TRUE ~ 0)) %>%
#   group_by(ID.match, Location, Tax) %>%
#   summarize(nb.otu.coi = sum(presabs),
#             nb.seq.coi = sum(value))
# preydiv.coi.nobac
# 
# ###
# ###23S data
# nobac.23s <- seqs23s %>%
#   filter(Phylum != "Bacillariophyta")
# cnames <- as.character(nobac.23s$ESV)
# sub23s.nobac <- nobac.23s %>%
#   #grab columns of fish gut specimens
#   select(., contains("UAE18")) %>%
#   rownames_to_column %>% 
#   gather(var, value, -rowname) %>% 
#   spread(rowname, value) %>%
#   set_colnames(c("ID.match", cnames)) %>%
#   join(guts.meta[c("Location", "Tax", "ID.match")], by = "ID.match") 
# 
# preydiv.23s.nobac <- sub23s.nobac %>%
#   pivot_longer(ESV_000034:ESV_036112, names_to = "ESVs") %>%
#   mutate(presabs = case_when(value > 0 ~ 1,
#                               TRUE ~ 0)) %>%
#   group_by(ID.match, Location, Tax) %>%
#   summarize(nb.esv.23s = sum(presabs),
#             nb.seq.23s = sum(value))
# preydiv.23s.nobac
# 
# preydiv.allprim.nobac <- inner_join(preydiv.coi.nobac, preydiv.23s.nobac, by = c("ID.match", "Location", "Tax")) %>%
#   mutate(ratio_tax = nb.otu.coi/nb.esv.23s,
#          ratio_seq = nb.seq.coi/nb.seq.23s,
#          tax_unit_sum = nb.otu.coi + nb.esv.23s) %>%
#   group_by(Location, Tax) %>%
#   summarize(mean_nbotu = mean(nb.otu.coi),
#             mean_nbesv = mean(nb.esv.23s),
#             mean_nbtotal = mean(tax_unit_sum),
#             mean_seq_coi = mean(nb.seq.coi),
#             mean_seq_23s = mean(nb.seq.23s),
#             mean_ratio_tax = mean(ratio_tax),
#             mean_ratio_seq = mean(ratio_seq)) %>%
#   arrange(Tax)
# preydiv.allprim.nobac


###################rarefaction

coi.meta <- coi.seqs %>%
  select(ID, UAE18005.1:UAE18867.1) %>%
  pivot_longer(cols = UAE18005.1:UAE18867.1) %>%
  pivot_wider(names_from = "ID", values_from = "value") %>%
  rename(ID.match = name) %>%
  left_join(preydiv.coi.nobac, by = "ID.match") %>%
  unite(Location, Tax, col = "ID", remove = F) %>%
  select(-nb.otu.coi, -nb.seq.coi) %>%
  select(ID, Location, Tax) 

coi.rare <- coi.seqs %>%
  select(ID, UAE18005.1:UAE18867.1) %>%
  pivot_longer(cols = UAE18005.1:UAE18867.1) %>%
  pivot_wider(names_from = "ID", values_from = "value") %>%
  rename(ID.match = name) %>%
  left_join(preydiv.coi.nobac, by = "ID.match") %>%
  unite(Location, Tax, col = "ID", remove = T)%>%
  select(-ID.match, -nb.otu.coi, -nb.seq.coi) %>%
  group_by(ID) %>%
  summarize_all(funs(sum(.))) %>%
  pivot_longer(cols = 2:547) %>%
  pivot_wider(names_from = "ID", values_from = "value")


coi.rare1 <- as.data.frame(coi.rare)
rownames(coi.rare1) <- coi.rare1$name
coi.seqs.nt <- coi.rare1[-1]


coi.seqs.list = as.data.frame(t(coi.seqs.nt))
str(coi.seqs.list)

coi.list2 <- as.data.frame(coi.seqs.list)


# split dataframe into list, with each ARMS as an element
coi.list.split <- split(coi.list2, rownames(coi.list2))
coi.list.t <- lapply(coi.list.split, t)

# rarefaction curves by samples
rarefactioncoi <- iNEXT(coi.list.t, q=0, datatype="abundance", size=NULL, endpoint=max(colSums(coi.rare[-1])), knots=50, se=TRUE, conf=0.95, nboot=100);beep(sound = 7)
rarefactioncoi


rare <- fortify(rarefactioncoi, type=1) %>%
  rename(ID = site)
rare.meta <- rare %>%
  inner_join(coi.meta)
head(rare.meta)

rare.point <-rare.meta[which(rare.meta$method=="observed"),]
rare.line <-rare.meta[which(rare.meta$method!="observed"),]
rare.line$method <- factor(rare.line$method, c("interpolated", "extrapolated"), c("interpolation", "extrapolation"))

rarefactionplot.coi <- ggplot(rare.meta, aes(x=x, y=y, color=Location)) +
geom_line(aes(linetype=method), lwd=0.5, data=rare.line) + geom_ribbon(aes(ymin=y.lwr, ymax=y.upr,fill=Location, color=NULL), alpha=0.2) + labs(x="Number of sequences", y="Number of OTUs") +
  theme_bw() + theme(plot.title = element_text(size = 8),
          axis.text = element_text(color = "black", size = 8, family = "Arial"),
          axis.title = element_text(color = "black", size = 8, family = "Arial"),
          legend.title=element_text(size=8), 
          legend.text=element_text(size=8)) +
  facet_wrap(.~Tax) +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  ggtitle("(a)")
  
rarefactionplot.coi


###23S
meta23s <- seqs23s %>%
  select(ESV, UAE18005.1:UAE18867.1) %>%
  pivot_longer(cols = UAE18005.1:UAE18867.1) %>%
  pivot_wider(names_from = "ESV", values_from = "value") %>%
  rename(ID.match = name) %>%
  left_join(preydiv.23s.nobac, by = "ID.match") %>%
  unite(Location, Tax, col = "ID", remove = F) %>%
  select(-nb.esv.23s, -nb.seq.23s) %>%
  select(ID, Location, Tax) 

rare23s <- seqs23s %>%
  select(ESV, UAE18005.1:UAE18867.1) %>%
  pivot_longer(cols = UAE18005.1:UAE18867.1) %>%
  pivot_wider(names_from = "ESV", values_from = "value") %>%
  rename(ID.match = name) %>%
  left_join(preydiv.23s.nobac, by = "ID.match") %>%
  unite(Location, Tax, col = "ID", remove = T)%>%
  select(-ID.match, -nb.esv.23s, -nb.seq.23s) %>%
  group_by(ID) %>%
  summarize_all(funs(sum(.))) %>%
  pivot_longer(cols = 2:3007) %>%
  pivot_wider(names_from = "ID", values_from = "value")

max(colSums(rare23s[-1]))


rare123s <- as.data.frame(rare23s)
rownames(rare123s) <- rare123s$name
seqs23snt <- rare123s[-1]


seqs23slist = as.data.frame(t(seqs23snt))
str(seqs23slist)

seqs23slist2 <- as.data.frame(seqs23slist)


# split dataframe into list, with each ARMS as an element
list23ssplit <- split(seqs23slist, rownames(seqs23slist))
list23st <- lapply(list23ssplit, t)

# rarefaction curves by samples
rarefaction23s <- iNEXT(list23st, q=0, datatype="abundance", size=NULL, endpoint=max(colSums(rare23s[-1])), knots=50, se=TRUE, conf=0.95, nboot=100);beep(sound = 8)
rarefaction23s


rarified23s <- fortify(rarefaction23s, type=1) %>%
  rename(ID = site)
rare23smeta <- rarified23s %>%
  inner_join(meta23s)
head(rare23smeta)

rare23spoint <-rare23smeta[which(rare23smeta$method=="observed"),]
rare23sline <-rare23smeta[which(rare23smeta$method!="observed"),]
rare23sline$method <- factor(rare23sline$method, c("interpolated", "extrapolated"), c("interpolation", "extrapolation"))

rarefactionplot23s <- ggplot(rare23smeta, aes(x=x, y=y, color=Location)) + 
geom_line(aes(linetype=method), lwd=0.5, data=rare23sline) + 
  geom_ribbon(aes(ymin=y.lwr, ymax=y.upr,fill=Location, color=NULL), alpha=0.2) + labs(x="Number of sequences", y="Number of ESVs") +
  theme_bw() + theme(plot.title = element_text(size = 8),
          axis.text = element_text(color = "black", size = 8, family = "Arial"),
          axis.title = element_text(color = "black", size = 8, family = "Arial"),
          legend.title=element_text(size=8), 
          legend.text=element_text(size=8)) +
  facet_wrap(.~Tax) +
    scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  ggtitle("(b)")
rarefactionplot23s

rarelegend<-g_legend(rarefactionplot23s)

rarefactionplots <- gbm::grid.arrange(mylegend, gridExtra::arrangeGrob(rarefactionplot.coi + theme(legend.position="none"),
                         rarefactionplot23s + theme(legend.position="none"),
                         nrow=2),
            nrow=2, heights=c(1, 12))

Fig4 <- gridExtra::arrangeGrob(rarefactionplot.coi + theme(legend.position="none"),
                               rarefactionplot23s + theme(legend.position="none"), 
                               nrow = 2)

ggsave("Plots/Fig4_MS.png", plot = Fig4, width = 5, height = 6)
```




```{r GROWTH MODELING}
# Load package
library(sdmpredictors)
library(rasterVis)

my.sites <- comms %>%
  group_by(Location, Site) %>%
  summarize(Lon = mean(Long), Lat = mean(Lat)) %>%
  as.data.frame(.) %>%
  unite("Name", c(Location, Site), remove = F) %>%
  arrange(Name)
layers <- list_layers(marine = TRUE)
environment.bottom <- load_layers(c("MS_biogeo15_sst_max_5m",
                                    "MS_biogeo14_sst_min_5m",
                                    "MS_biogeo16_sst_range_5m",
                                    "BO_sstmean"),
                                  equalarea=FALSE, rasterstack=TRUE)

environment.vars <- data.frame(Name=my.sites$Name, extract(environment.bottom, my.sites[,4:5]))
environment.vars

# Crop raster to fit the North Atlantic
middleeast <- extent(50, 60, 20, 30)
temp.middleast <- crop(environment.bottom, middleeast)

#function to fortify data
gplot_data <- function(x, maxpixels = 500000)  {
  x <- raster::sampleRegular(x, maxpixels, asRaster = TRUE)
  coords <- raster::xyFromCell(x, seq_len(raster::ncell(x)))
  ## Extract values
  dat <- utils::stack(as.data.frame(raster::getValues(x))) 
  names(dat) <- c('value', 'variable')

  dat <- dplyr::as.tbl(data.frame(coords, dat))

  if (!is.null(levels(x))) {
    dat <- dplyr::left_join(dat, levels(x)[[1]], 
                            by = c("value" = "ID"))
  }
  dat
}

# apply function
fort.temp.middleeast <- gplot_data(temp.middleast)

mapdata.max = fort.temp.middleeast %>%
  filter(variable == "MS_biogeo15_sst_max_5m")


maxplot <- ggplot(data = mapdata.max, aes(x = x, y = y)) +
  geom_tile(aes(fill = value, color = value)) +
  geom_point(data = my.sites, aes(x = Lon, y = Lat), color = "black", size = 3, alpha = 0.85) +
  scale_fill_fish(option = "Trimma_lantana", na.value="white", name = "Temperature", begin = 0.65) +
  scale_color_fish(option = "Trimma_lantana", na.value="white", begin = 0.65, guide=FALSE) +
  theme_sjb() + theme(panel.grid.major  = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          legend.position = "top") +
  scale_y_continuous(limits = c(20, 30), breaks = seq(20, 30, 2.5), expand = c(0,0)) +
  scale_x_continuous(limits = c(50, 60), breaks = seq(50, 60, 2.5), expand = c(0,0)) +
  xlab("Longitude") +
  ylab("Latitude") +
  annotate("text", x = 53.5, y = 26, size = 4, label = "ARABIAN GULF", color = "black", fontface = 2) +
  annotate("text", x = 58.5, y = 24.5, size = 4, label = "GULF OF OMAN", color = "black", fontface = 2) +
  annotate("text", x = 52, y = 30, size = 4, label = "a) Maximum", color = "black", fontface = 2) +
  coord_cartesian(clip="off")
maxplot


mapdata.min = fort.temp.middleeast %>%
  filter(variable == "MS_biogeo14_sst_min_5m")


minplot <- ggplot(data = mapdata.min, aes(x = x, y = y)) +
  geom_tile(aes(fill = value, color = value)) +
  geom_point(data = my.sites, aes(x = Lon, y = Lat), color = "black", size = 3, alpha = 0.85) +
  scale_fill_fish(option = "Trimma_lantana", na.value="white", name = "Temperature", end = 0.35) +
  scale_color_fish(option = "Trimma_lantana", na.value="white", end = 0.35, guide=FALSE) +
  theme_sjb() + theme(panel.grid.major  = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          legend.position = "top") +
  scale_y_continuous(limits = c(20, 30), breaks = seq(20, 30, 2.5), expand = c(0,0)) +
  scale_x_continuous(limits = c(50, 60), breaks = seq(50, 60, 2.5), expand = c(0,0)) +
  xlab("Longitude") +
  ylab("Latitude") +
  annotate("text", x = 53.5, y = 26, size = 4, label = "ARABIAN GULF", color = "black", fontface = 2) +
  annotate("text", x = 58.5, y = 24.5, size = 4, label = "GULF OF OMAN", color = "black", fontface = 2) +
  annotate("text", x = 52, y = 30, size = 4, label = "b) Minimum", color = "black", fontface = 2) +
  coord_cartesian(clip="off")
minplot


mapdata.range = fort.temp.middleeast %>%
  filter(variable == "MS_biogeo16_sst_range_5m")


rangeplot <- ggplot(data = mapdata.range, aes(x = x, y = y)) +
  geom_tile(aes(fill = value, color = value)) +
  geom_point(data = my.sites, aes(x = Lon, y = Lat), color = "black", size = 3, alpha = 0.85) +
  scale_fill_fish(option = "Trimma_lantana", na.value="white", name = "Temperature") +
  scale_color_fish(option = "Trimma_lantana", na.value="white", guide=FALSE) +
  theme_sjb() + theme(panel.grid.major  = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          legend.position = "top") +
  scale_y_continuous(limits = c(20, 30), breaks = seq(20, 30, 2.5), expand = c(0,0)) +
  scale_x_continuous(limits = c(50, 60), breaks = seq(50, 60, 2.5), expand = c(0,0)) +
  xlab("Longitude") +
  ylab("Latitude") +
  annotate("text", x = 53.5, y = 26, size = 4, label = "ARABIAN GULF", color = "black", fontface = 2) +
  annotate("text", x = 58.5, y = 24.5, size = 4, label = "GULF OF OMAN", color = "black", fontface = 2) +
  annotate("text", x = 52, y = 30, size = 4, label = "c) Range", color = "black", fontface = 2) +
  coord_cartesian(clip="off")
rangeplot

temp_plots <- ggarrange(maxplot, minplot, rangeplot, ncol = 3, nrow = 1)
temp_plots
ggsave("Plots/temperature_plots.pdf", temp_plots, width = 14, height = 6, useDingbats = F)

# 
# growth.species <- read.csv("Data/Morais_DS1.csv")
# growth.group <- read.csv("Data/Morais_DS2.csv")
# 
# growth.fam <- growth.species %>%
#   group_by(Family) %>%
#   summarize(Kmaxmean = mean(Kmax), LinfTLmean = mean(LinfTL), SSTmean = mean(sstmean))
# 
# growth.group.avg <- growth.group %>%
#   group_by(MaxSizeTL, sstmean) %>%
#   summarize(Kmaxmean = mean(Kmax), lwrmean = mean(Kmax_lowqt), uprmean = mean(Kmax_upqt))
# 
# growthmod <- brm(log(Kmax) ~ (log(LinfTL) * log(sstmean)), data = growth.species, control = list(adapt_delta = 0.90, max_treedepth = 11), iter = 4000)
# summary(growthmod)
# plot(growthmod)
# 
# growth.pred <- growth.species %>%
#   data_grid(LinfTL = unique(comms$TL)/10, 
#             sstmean = c(unique(comms.post$BO2_tempmax_bdmean), unique(comms.post$BO2_tempmean_bdmean), unique(comms.post$BO2_tempmin_bdmean))) %>%
#   add_predicted_draws(growthmod, n = 50) %>%
#   mutate(meankmaxback = exp(.prediction)) %>%
#   group_by(LinfTL, sstmean) %>%
#   summarize(meankmax = mean(meankmaxback), sdkmax = sd(meankmaxback)) 
# growth.pred
# 
# growth.simul <- comms.post %>%
#   inner_join(growth.pred, by = c("LinfTL", "sstmean"))
#     
#   add_predicted_draws(biomass.model, n = 1000) %>%
#   mutate(pred.biomass = exp(.prediction))
# 
# 
# bio.pred.plot <- ggplot(data = bio.pred) +
#   geom_halfeyeh(aes(y = rev(Location), x = pred.biomass, fill = Location)) +
#   geom_jitter(aes(x = Biomass_per_m2, y = site_intercepts, shape = reorder(Site, sort(as.numeric(site_intercepts))), fill = Location), color = "black", 
#              data = comm_means, height = 0.02, 
#              alpha = 0.5, size = 2) +
#   scale_color_manual(values = c("dodgerblue4", "mediumaquamarine")) +
#   scale_fill_manual(values = alpha(c("dodgerblue4", "mediumaquamarine"), 0.5)) +
#   scale_shape_manual(name = "Site", values = c(21,22,23,21,22,23)) +
#   scale_x_log10(limits = c(0.1,1e3), breaks=c(0,0.1,1,10,1000), labels=c(0,0.1,1,10,1000)) +
#   theme_bw() +
#   theme(axis.text.y = element_blank(), 
#         axis.ticks.y = element_blank(),
#         axis.title.y = element_blank(),
#         legend.position = "top") +
#   guides(fill = guide_legend(nrow = 1),
#          shape = guide_legend(nrow = 1)) +
#   xlab(expression(paste("Biomass of cryptobenthic fishes (grams ", m^{-2},")")))
# bio.pred.plot
# 
# x = as.data.frame(table(growth.species$LinfTL, growth.species$sstmean)) %>%
#   filter(Freq > 0) %>%
#   arrange(Var1, Var2)
```

``` {r BENTHIC COMPOSITION}
table(benthcomm$category)

benth.tidy <- benthcomm %>%
  mutate(category_tidy = case_when(category == "livecoral_encrusting" ~ "livecoral_other",
                                   category == "livecoral_foliose" ~ "livecoral_other",
                                   category == "livecoral_massive" ~ "livecoral_other",
                                   TRUE ~ as.character(category))) %>%
  filter(category != "unidentifiable") %>% 
  group_by(category) %>%
  mutate(total_cat = n()) %>%
  ungroup() %>%
  filter(total_cat >= 5) %>%
  group_by(location, site, sitename, category_tidy) %>%
  summarize(total = n()) %>%
  ungroup() %>%
  group_by(location, site, sitename) %>%
  mutate(category_percent = total/sum(total)) %>%
  dplyr::select(-total) %>%
  pivot_wider(names_from = category_tidy, values_from = category_percent,
    values_fill = list(category_percent = 0))


benth.cc <- benth.tidy %>%
  dplyr::select(location, site, sitename, livecoral_other, livecoral_branching) %>%
  mutate(total_cc = livecoral_other+livecoral_branching)

###run mds
benth.mds <- metaMDS(benth.tidy[-c(1:4)], metric = "manhattan", trymax = 1000)
benth.mds
stressplot(benth.mds)

###get values and plot in ggplot
site.scores.benth <- as.tibble(scores(benth.mds)) %>%
  mutate(location = benth.tidy$location,
         site = benth.tidy$site,
         sitename = benth.tidy$sitename) %>% 
  inner_join(benth.tidy) %>%
  mutate(ordervar = case_when(site == "Dhabiya" ~ 1,
                              site == "RasGhanada" ~ 2,
                              site == "Saadiyat" ~ 3,
                              site == "Dibba" ~ 4,
                              site == "Sharm" ~ 5,
                              site == "Snoopy" ~ 6)) %>%
  mutate(Coral_cover = livecoral_other + livecoral_branching)


mds.points.benth <- as.data.frame(scores(benth.mds, "species")) %>%
  add_column(category = rownames(.))

point.plot.benth <- ggplot(mds.points.benth) +
  theme_sjb() +
  geom_segment(aes(x=0, xend=NMDS1, y=0, yend=NMDS2),
               arrow = arrow(length = unit(0.3, "cm")), color = "grey69",
               inherit.aes = F) +
  theme(legend.position = "top") +
  geom_text_repel(aes(x=NMDS1, NMDS2, label=category), size=4, inherit.aes = F) +
  scale_y_continuous(limits = c(-0.75, 0.75), breaks = seq(-0.75, 0.75, 0.25)) +
  scale_x_continuous(limits = c(-1.2, 1.2)) +
  xlab("NMDS1") +
  ylab("NMDS2")
point.plot.benth
###create convex hulls function
convex_hull <- function(site.scores.benth) site.scores.benth[chull(site.scores.benth$NMDS1, site.scores.benth$NMDS2),] 

###run convex hulls on habitats
site_hulls <- ddply(site.scores.benth, "site", convex_hull)


###create vector with habitat names in center of convex hulls
site_centers <- site_hulls %>% group_by(site) %>% summarize(NMDS1 = mean(NMDS1), NMDS2 = mean(NMDS2))

###plot mds results
# plot one species name
comp.plot.benth <- ggplot(site.scores.benth, aes(x = NMDS1, y = NMDS2)) +
  #overlay convex hulls
  #overlay points
  geom_point(aes(color = location, group = location, fill = location, size = Coral_cover,
                             shape = reorder(site, sort(as.numeric(ordervar))))) +
    geom_polygon(data = site_hulls, aes(x = NMDS1, y = NMDS2, 
                                         fill = location,
                                         group = site),
               alpha = 0.4, lty = 1, lwd = 0.1, color = "black") +
    geom_segment(data = mds.points.benth, aes(x=0, xend=NMDS1, y=0, yend=NMDS2),
               arrow = arrow(length = unit(0.3, "cm")), color = "grey69",
               inherit.aes = F) +
  theme(legend.position = "top") +
  geom_text_repel(data = mds.points.benth, aes(x=NMDS1, NMDS2, label=category), size=4, inherit.aes = F) +
  theme_bw()+
  theme(legend.position = "top",
        legend.title.align = 0,
        legend.box = "horizontal") +
  scale_color_manual(values = uaecols) +
  scale_fill_manual(values = uaecols) +
  scale_shape_manual(name = "Site", values = c(21,22,23,21,22,23)) +
    guides(fill = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1)) +
    scale_y_continuous(limits = c(-0.75, 0.75), breaks = seq(-0.75, 0.75, 0.25)) +
  scale_x_continuous(limits = c(-1.2, 1.2)) +
  xlab("NMDS1") +
  ylab("NMDS2")

comp.plot.benth


#run GLM with abundance data and offset for surface area sampled
cc.model <- brm(logit_scaled(benth.cc) ~ location + (1|site), 
                            data = benth.cc.mod, control = list(adapt_delta = 0.999, max_treedepth = 15))
summary(cc.model)

ggsave("Plots/BenthicPlot.pdf", plot = comp_plot, width = 6, height = 4, useDingbats = FALSE)

```